PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
PREFIX rev:<http://purl.org/stuff/rev#>
SELECT *
WHERE {
    ?Review bsbm:reviewFor ?Product .
    ?Review dc:title ?Title .
    ?Review rev:text ?Text .
}

