PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
SELECT *
WHERE {
    ?Product rdfs:label ?Label .
    ?Product rdfs:comment ?Comment .
    ?Product bsbm:producer ?P .
    ?P rdfs:label ?Producer .
    ?Product dc:publisher ?P .
    ?Product bsbm:productPropertyTextual1 ?PropertyTextual1 .
    ?Product bsbm:productPropertyNumeric1 ?PropertyNumeric1 .
}

