PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
PREFIX rev:<http://purl.org/stuff/rev#>
SELECT *
WHERE {
    ?Review_9_1 bsbm:reviewFor ?Product_9_1 .
    ?Review_9_1 dc:title ?Title_9_1 .
    ?Review_9_1 rev:text ?Text_9_1 .
}

