PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
SELECT *
WHERE {
    ?Product_5_4 rdfs:label ?Label_5_4 .
    ?Product_5_4 rdfs:comment ?Comment_5_4 .
    ?Product_5_4 bsbm:producer ?P_5_4 .
    ?P_5_4 rdfs:label ?Producer_5_4 .
    ?Product_5_4 dc:publisher ?P_5_4 .
    ?Product_5_4 bsbm:productPropertyTextual1 ?PropertyTextual1_5_4 .
    ?Product_5_4 bsbm:productPropertyNumeric1 ?PropertyNumeric1_5_4 .
}

