PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
SELECT *
WHERE {
    ?Product_6_3 rdfs:label ?ProductLabel_6_3 .
    ?Offer_6_3 bsbm:product ?Product_6_3 .
    ?Offer_6_3 bsbm:price ?Price_6_3 .
    ?Offer_6_3 bsbm:vendor ?Vendor_6_3 .
}

