PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
SELECT *
WHERE {
    ?Product_14_1 rdfs:label ?ProductLabel_14_1 .
    ?Offer_14_1 bsbm:product ?Product_14_1 .
    ?Offer_14_1 bsbm:price ?Price_14_1 .
    ?Offer_14_1 bsbm:vendor ?Vendor_14_1 .
    ?Offer_14_1 bsbm:deliveryDays ?DeliveryDays_14_1 .
    ?Offer_14_1 bsbm:validTo ?Date_14_1 .
}

