PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
SELECT *
WHERE {
    ?Product_13_4 rdfs:label ?ProductLabel_13_4 .
    ?Offer_13_4 bsbm:product ?Product_13_4 .
    ?Offer_13_4 bsbm:price ?Price_13_4 .
    ?Offer_13_4 bsbm:vendor ?Vendor_13_4 .
    ?Offer_13_4 bsbm:offerWebpage ?OfferURL_13_4 .
    ?Vendor_13_4 foaf:homepage ?Vendorhomepage_13_4 .
}
