PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
SELECT *
WHERE {
    ?Product_12_0 rdfs:label ?Label_12_0 .
    ?Product_12_0 rdfs:comment ?Comment_12_0 .
    ?Product_12_0 bsbm:producer ?P_12_0 .
    ?P_12_0 rdfs:label ?Producer_12_0 .
    ?Product_12_0 dc:publisher ?P_12_0 .
    ?Product_12_0 bsbm:productPropertyTextual3 ?PropertyTextual3_12_0 .
    ?Product_12_0 bsbm:productPropertyNumeric3 ?PropertyNumeric3_12_0 .
}

