PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
SELECT *
WHERE {
    ?Product_3_4 bsbm:producer ?P_3_4 .
    ?P_3_4 rdfs:label ?Producer_3_4 .
    ?Product_3_4 dc:publisher ?P_3_4 .
    ?Product_3_4 bsbm:productFeature ?F_3_4 .
}

