PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
SELECT *
WHERE {
    ?Product_13_3 rdfs:label ?ProductLabel_13_3 .
    ?Offer_13_3 bsbm:product ?Product_13_3 .
    ?Offer_13_3 bsbm:price ?Price_13_3 .
    ?Offer_13_3 bsbm:vendor ?Vendor_13_3 .
    ?Offer_13_3 bsbm:offerWebpage ?OfferURL_13_3 .
    ?Vendor_13_3 foaf:homepage ?Vendorhomepage_13_3 .
}
