PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
PREFIX rev:<http://purl.org/stuff/rev#>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
SELECT *
WHERE {
    ?Offer_15_4 bsbm:product ?Product_15_4 .
    ?Offer_15_4 bsbm:price ?Price_15_4 .
    ?Offer_15_4 bsbm:vendor ?Vendor_15_4 .
    ?Vendor_15_4 rdfs:label ?VendorTitle_15_4 .
    ?Vendor_15_4 bsbm:country ?Country_15_4 .
    ?Offer_15_4 dc:publisher ?Vendor_15_4 .
    ?Review_15_4 bsbm:reviewFor ?Product_15_4 .
    ?Review_15_4 rev:reviewer ?Reviewer_15_4 .
    ?Reviewer_15_4 foaf:name ?RevName_15_4 .
}

