PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
SELECT *
WHERE {
    ?Product_11_1 rdfs:label ?Label_11_1 .
    ?Product_11_1 rdfs:comment ?Comment_11_1 .
    ?Product_11_1 bsbm:producer ?P_11_1 .
    ?P_11_1 rdfs:label ?Producer_11_1 .
    ?Product_11_1 dc:publisher ?P_11_1 .
    ?Product_11_1 bsbm:productPropertyTextual2 ?PropertyTextual2_11_1 .
    ?Product_11_1 bsbm:productPropertyNumeric2 ?PropertyNumeric2_11_1 .
}

