PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
PREFIX rev:<http://purl.org/stuff/rev#>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
SELECT *
WHERE {
    ?Product_7_4 rdfs:label ?ProductLabel_7_4 .
    ?Review_7_4 bsbm:reviewFor ?Product_7_4 .
    ?Review_7_4 rev:reviewer ?Reviewer_7_4 .
    ?Reviewer_7_4 foaf:name ?RevName_7_4 .
    ?Review_7_4 dc:title ?RevTitle_7_4 .
}

