PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
SELECT *
WHERE {
    ?Product_14_0 rdfs:label ?ProductLabel_14_0 .
    ?Offer_14_0 bsbm:product ?Product_14_0 .
    ?Offer_14_0 bsbm:price ?Price_14_0 .
    ?Offer_14_0 bsbm:vendor ?Vendor_14_0 .
    ?Offer_14_0 bsbm:deliveryDays ?DeliveryDays_14_0 .
    ?Offer_14_0 bsbm:validTo ?Date_14_0 .
}

