PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
PREFIX rev:<http://purl.org/stuff/rev#>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
SELECT *
WHERE {
    ?Offer_15_3 bsbm:product ?Product_15_3 .
    ?Offer_15_3 bsbm:price ?Price_15_3 .
    ?Offer_15_3 bsbm:vendor ?Vendor_15_3 .
    ?Vendor_15_3 rdfs:label ?VendorTitle_15_3 .
    ?Vendor_15_3 bsbm:country ?Country_15_3 .
    ?Offer_15_3 dc:publisher ?Vendor_15_3 .
    ?Review_15_3 bsbm:reviewFor ?Product_15_3 .
    ?Review_15_3 rev:reviewer ?Reviewer_15_3 .
    ?Reviewer_15_3 foaf:name ?RevName_15_3 .
}

