PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
SELECT *
WHERE {
    ?Product_2_4 rdf:type ?ProductType_2_4 .
    ?Product_2_4 bsbm:productFeature ?ProductFeature1_2_4 .
}

