PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
SELECT *
WHERE {
    ?Product_13_1 rdfs:label ?ProductLabel_13_1 .
    ?Offer_13_1 bsbm:product ?Product_13_1 .
    ?Offer_13_1 bsbm:price ?Price_13_1 .
    ?Offer_13_1 bsbm:vendor ?Vendor_13_1 .
    ?Offer_13_1 bsbm:offerWebpage ?OfferURL_13_1 .
    ?Vendor_13_1 foaf:homepage ?Vendorhomepage_13_1 .
}
