PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc:<http://purl.org/dc/elements/1.1/>
SELECT *
WHERE {
    ?Product_12_1 rdfs:label ?Label_12_1 .
    ?Product_12_1 rdfs:comment ?Comment_12_1 .
    ?Product_12_1 bsbm:producer ?P_12_1 .
    ?P_12_1 rdfs:label ?Producer_12_1 .
    ?Product_12_1 dc:publisher ?P_12_1 .
    ?Product_12_1 bsbm:productPropertyTextual3 ?PropertyTextual3_12_1 .
    ?Product_12_1 bsbm:productPropertyNumeric3 ?PropertyNumeric3_12_1 .
}

