/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package experimentseswc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UNION = 4;
  /** RegularExpression Id. */
  int FILTER = 5;
  /** RegularExpression Id. */
  int OPTIONAL = 6;
  /** RegularExpression Id. */
  int SELECT = 7;
  /** RegularExpression Id. */
  int DISTINCT = 8;
  /** RegularExpression Id. */
  int WHERE = 9;
  /** RegularExpression Id. */
  int PREFIX = 10;
  /** RegularExpression Id. */
  int CONSTANT = 11;
  /** RegularExpression Id. */
  int VARIABLE = 12;
  /** RegularExpression Id. */
  int LKEY = 13;
  /** RegularExpression Id. */
  int LPAR = 14;
  /** RegularExpression Id. */
  int RPAR = 15;
  /** RegularExpression Id. */
  int COLON = 16;
  /** RegularExpression Id. */
  int RKEY = 17;
  /** RegularExpression Id. */
  int POINT = 18;
  /** RegularExpression Id. */
  int OPERATOR = 19;
  /** RegularExpression Id. */
  int URI = 20;
  /** RegularExpression Id. */
  int ALL = 21;
  /** RegularExpression Id. */
  int A = 22;
  /** RegularExpression Id. */
  int ID = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<UNION>",
    "<FILTER>",
    "<OPTIONAL>",
    "<SELECT>",
    "<DISTINCT>",
    "<WHERE>",
    "<PREFIX>",
    "<CONSTANT>",
    "<VARIABLE>",
    "\"{\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "<RKEY>",
    "\".\"",
    "<OPERATOR>",
    "<URI>",
    "\"*\"",
    "\"a\"",
    "<ID>",
  };

}
