PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
SELECT * 
WHERE {
    ?Product rdfs:label ?Label .
    ?Product rdf:type ?ProductType .
    ?Product bsbm:productFeature ?ProductFeature1 .
}

