PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
SELECT * 
WHERE {
    ?Offer bsbm:product ?ProductURI .
    ?ProductURI rdfs:label ?Productlabel .
    ?Offer bsbm:vendor ?VendorURI .
    ?Offer bsbm:price ?Price .
}

